apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  selector:
    matchLabels:
      app: cloud
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - name: cloud
        image: cloud:v1
