FROM ubuntu
  
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /app
RUN apt-get update
RUN apt install -y python3-dev \
    python3-pip \
    python3-opencv \
    vim-tiny \ 
    libopencv-dev\
    python3-numpy\
    iputils-ping 
RUN pip3 install numpy
RUN pip3 install paho-mqtt
RUN pip3 install opencv-contrib-python
RUN pip3 install opencv-python
RUN pip3 install boto3
COPY cloud_listener.py .

#CMD ["export", "DISPLAY=:0"]
#CMD ["xhost", "+local:root]
CMD ["python3","dog_cloud.py"]
